site_name: IS&S Documentation
site_url: ""
use_directory_urls: False
nav:
    - Home: index.md
    - Policies: iss_policies.md
    - Office 365: procedures/office365.md
    - Backups: procedures/backups.md
    - Parts ordering: procedures/dell_ordering.md
    - Windows Bypass: os_fixes/sethc_bypass.md
    - About: about.md

theme: readthedocs
